[project]
name = "tensornetwork"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pybind11"
]

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
minimum-version = "0.10"
build-dir = "build/{wheel_tag}"

